### PR TITLE
Return explanations along with stattype guesses

### PR DESCRIPTION
**Pull request by asilversempirical**

### CODE REVIEW

**Comment by fsaad** [comment]
The `enum` module is not available until python 3.4, causing both the test suite and users on python 2.7 to crash.

**Comment by fsaad** [comment]
The following pip package claims to provide a backport: https://pypi.python.org/pypi/enum34

Although there is an easy way to achieve what we are doing with Enum (statistical types) without using Enums i.e. just create a dict.

**Comment by asilversempirical** [comment]
That's weird. I'm running 2.7 and was working fine. Give me a few minutes to poke around and I'll just convert these to strings unless I find some explanation. Sorry about that!

**Comment by asilversempirical** [comment]
Oh, look, something had pulled in enum34 and I just assumed it was part of the standard libs. PR on its way.

**Comment by asilversempirical** [comment]
Opened https://github.com/probcomp/bdbcontrib/pull/156

Again, sorry about that!

**Pull request merged**
