### PR TITLE
Fix the pandas dependency requirement.

### PR DESCRIPTION
**Pull request by fsaad**
Currently tests/test_parallel invokes pandas.DataFrame.sort_values
which is only available in 0.17.0

http://pandas.pydata.org/pandas-docs/version/0.17.0/generated/pandas.DataFrame.sort_values.html?highlight=sort_values#pandas.DataFrame.sort_values

so a user cannot run the tests with any lower version, which returns

E           AttributeError: 'DataFrame' object has no attribute 'sort_values'

Also, ensure code in test_parallel.py has consistent formatting in
two places that is both consistent with itself, and the bdbcontrib
conventions.

I kept this as a pull request so Grem, et al. can decide whether we actually are going to upgrade to a newer version of pandas, or change the test.

### CODE REVIEW

**Comment by riastradh-probcomp** [comment]
Date: Thu, 04 Feb 2016 16:48:55 -0800
   From: F Saad <notifications@github.com>

   Currently tests/test_parallel invokes pandas.DataFrame.sort_values
   which is only available in 0.17.0

   http://pandas.pydata.org/pandas-docs/version/0.17.0/generated/pandas.DataFrame.sort_values.html?highlight=sort_values#pandas.DataFrame.sort_values

   so a user cannot run the tests with any lower version, which returns

   E           AttributeError: 'DataFrame' object has no attribute 'sort_values'

What does sort_values do?  Can we just sorted(...) of the result?
Strong preference for not depending on the latest and greatest version
of everything, which gets in the way of anyone outside our group
actually trying to use our stuff.

**Comment by gregory-marton** [comment]
Am strongly inclined to accept the pr, because every user we have interacted with so far has been very happy to put our software into a virtual environment where our choices of library versions don't matter. This is, in fact, something of a necessity for working with the many packages that require many often conflicting versions of software.

@fsaad in the future I would appreciate the unrelated cosmetic changes to be in a separate commit. I also happen to disagree with you on the style preference. :-)  But it's fine for now.

**Comment by fsaad** [comment]
@gregory-marton RE: cosmetic changes

But I thought I was comprising with the style I put in as a middle ground between our preferences ... in particular, what I did is PEP8 compliant!
https://www.python.org/dev/peps/pep-0008/#indentation

The style I avoided in this commit (the non PEP8 style that we use in bayeslite/bdbcontrib) is
```
assert_frame_equal(parallel_sim, parallel_sim_2,
    check_column_type=True)
```
and instead I used the PEP8 style
```
assert_frame_equal(
    parallel_sim, parallel_sim_2, check_column_type=True)
```

**Comment by gregory-marton** [comment]
@fsaad Thanks. I had forgotten that conversation. I stand by my previous decision not to ask for any changes?

**Comment by fsaad** [comment]
Agree that such changes belong in a separate commit, thanks for the review.

**Pull request merged**
