### PR TITLE
Strip out use of enums and go back to strings to represent stattypes

### PR DESCRIPTION
**Pull request by asilversempirical**
The enum module isn't actually provided in base 2.7.

### CODE REVIEW

**Comment by fsaad** [comment]
The test suite fails

```
E           assert 'CREATE GENER...ol1" IGNORE);' == 'CREATE GENERA...CATEGORICAL);'
E             Skipping 118 identical leading characters in diff, use -v to show
E             - ATEGORICAL,"col3" IGNORE,"col1" IGNORE);
E             + ATEGORICAL);

tests/test_mml_utils.py:62: AssertionError
```

Does it pass on your machine?

@gregory-marton are you not making use of the Jenkins job `bdbcontrib-pull-requests`? At the very least we need to ensure that pull requests are run against the Jenkins test suite to minimize the friction between contributor and Jenkins machine configuration to verify the merge happens smoothly.

**Comment by gregory-marton** [comment]
@fsaad, No, I'm not using the bdbcontrib-pull-requests jenkins job. I'm trusting @asilversempirical to have run ./check.sh appropriately. I'm also happy to have things like this fail as long as @asilversempirical is paying attention to the jenkins job after push and commits to making it green again. https://probcomp-4.csail.mit.edu/job/bdbcontrib-tests/

Users who rely on things being stable can and should use the last-green version.

I think that's consistent with expectations for light review: http://tinyurl.com/probcomp-review-standards

**Comment by gregory-marton** [comment]
@asilversempirical please feel free to push minor fixes like this without review.

**Comment by fsaad** [comment]
Agree RE: feel free to push minor fixes w/out review.

**Comment by asilversempirical** [comment]
Great, thanks for your patience. ./check.sh was clean, but after uninstalling bdbcontrib and reinstalling I see the breakage. Not sure where that came from, but I'm cleaning it up. Will push shortly.

I'm getting a certificate error trying to access https://probcomp-4.csail.mit.edu/job/bdbcontrib-tests/. Is that a known issue?

**Comment by fsaad** [comment]
> I'm getting a certificate error trying to access https://probcomp-4.csail.mit.edu/job/bdbcontrib-tests/. Is that a known issue?

Known issue. Still not sure why that page is public on the net anyway.

**Comment by asilversempirical** [comment]
Oh, whoops. Looks like I don't have push access to the repo, so this came your way anyway: https://github.com/probcomp/bdbcontrib/pull/157

**Pull request merged**
